version: "3"
services:
  nginx: 
    image: nginx:latest
    container_name: noise-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    restart: always
    
  webserver:
    build: ./
    container_name: noise-webapp
    restart: always
